version: "3.8"

services:
  localstack:
    container_name: "localstack_home_sruff"
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=1
      - LAMBDA_RUNTIME_EXECUTOR=docker #docker-reuse
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=us-east-1
    volumes:
      - ./local-stack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"