[package]
name = "config-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenvy = "0.15.6"
config = { version = "0.13.1" }
thiserror = "1.0.38"
serde = "1.0.136"
async-trait = "0.1.66"

