/*
 * auth-service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddUserResponse {
    #[serde(rename = "user")]
    pub user: Box<crate::models::User>,
}

impl AddUserResponse {
    pub fn new(user: crate::models::User) -> AddUserResponse {
        AddUserResponse {
            user: Box::new(user),
        }
    }
}


