/*
 * auth-service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact:
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AddUserRequest {
    #[serde(rename = "admin")]
    pub admin: bool,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "password")]
    pub password: String,
    #[serde(rename = "username")]
    pub username: String,
}

impl AddUserRequest {
    pub fn new(admin: bool, email: String, password: String, username: String) -> AddUserRequest {
        AddUserRequest {
            admin,
            email,
            password,
            username,
        }
    }
}
