/*
 * rust-lambda
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pengwin4@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CommandRequest {
    #[serde(rename = "command")]
    pub command: String,
}

impl CommandRequest {
    pub fn new(command: String) -> CommandRequest {
        CommandRequest {
            command,
        }
    }
}


