/*
 * auth-service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProfileResponse {
    #[serde(rename = "username")]
    pub username: String,
}

impl ProfileResponse {
    pub fn new(username: String) -> ProfileResponse {
        ProfileResponse {
            username,
        }
    }
}


