/*
 * auth-service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact:
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct User {
    #[serde(rename = "created_utc")]
    pub created_utc: String,
    #[serde(rename = "is_admin")]
    pub is_admin: bool,
    #[serde(rename = "updated_utc")]
    pub updated_utc: String,
    #[serde(rename = "user_id")]
    pub user_id: uuid::Uuid,
    #[serde(rename = "username")]
    pub username: String,
}

impl User {
    pub fn new(
        created_utc: String,
        is_admin: bool,
        updated_utc: String,
        user_id: uuid::Uuid,
        username: String,
    ) -> User {
        User {
            created_utc,
            is_admin,
            updated_utc,
            user_id,
            username,
        }
    }
}
