version: "3.8"

services:
  openapi-generator:
    image: openapitools/openapi-generator-cli:v7.0.0-beta
    volumes:
      - ./:/local
      - ../../../home-stuff/:/front

  diagrams:
    build: ./docs/diagrams/docker
    volumes:
      - ./doc/diagrams:/diagrams
