version: "3.8"

services:
  openapi-generator:
    image: openapitools/openapi-generator-cli:latest
    volumes:
      - ./:/local

  diagrams:
    build: ./docs/diagrams/docker
    volumes:
      - ./doc/diagrams:/diagrams
